### PR TITLE
Update to version 1.12.

### PR DESCRIPTION
**Pull request by saukko**
[taglib] Update to version 1.12. Fixes JB#55135

Update multilib patch from fedora.

Signed-off-by: Marko Saukko <marko.saukko@jolla.com>

### CODE REVIEW

**Review by mlehtima — APPROVED** [review]

**Comment by mlehtima** [comment]
This is not using a mirror for the submodule, should that be done?

**Comment by Thaodan** [comment]
Please change the spec file to use %make and %make_install while you are at it.

**Comment by mlehtima** [comment]
That first one should be %make_build (which makes the %{?_smp_mflags} not needed anymore)

**Comment by saukko** [comment]
> This is not using a mirror for the submodule, should that be done?

There wasn't taglib mirror thus didn't change, but yes it should. @xfade can you add?

**Comment by saukko** [comment]
> Please change the spec file to use %make and %make_install while you are at it.

%make_build for first one works fine.

%make_install does not work for some reason nor does %make install in my environment for this package.

**Comment by Thaodan** [comment]
> > Please change the spec file to use %make and %make_install while you are at it.
> 
> %make_build for first one works fine.
> 
> %make_install does not work for some reason nor does %make install in my environment for this package.

Oh yeah I forgot that we have a patched %make_install which breaks this. make would be %__make[1]

--

[1] https://github.com/rpm-software-management/rpm/blob/master/macros.in#L43

**Review by mkosola — APPROVED** [review]

**Pull request merged**
